services:
  app:
    build: .
    container_name: authtemplate_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      cache:
        condition: service_started
      db:
        condition: service_healthy

    restart: always

  db:
    image: postgres:16
    container_name: authtemplate_db
    restart: always
    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8
    container_name: authtemplate_cache
    restart: always
