services:
  app:
    build: .
    container_name: authtemplate_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: authtemplate_db
    restart: unless-stopped
    env_file:
      - .env

  cache:
    image: redis:8
    container_name: authtemplate_cache
    restart: unless-stopped
